CREATE TABLE MSTR_COACH_CENTER(
    MC_CENTER_ID VARCHAR(100) PRIMARY KEY
    ,MIC_CENTER_NM VARCHAR(100) NOT NULL
    ,MIC_CENTER_ADDRESS VARCHAR(300)
    ,MIC_CENTER_CITY VARCHAR(300) NOT NULL
    ,MIC_CENTER_STATE VARCHAR(100) NOT NULL
    ,MIC_CENTER_PIN INT NOT NULL
    ,MIC_CENTER_COUNTRY VARCHAR(100) NOT NULL
    ,MIC_CENTER_EMAILID VARCHAR(200) NOT NULL
    ,MIC_CENTER_CONTACTNO VARCHAR(100) NOT NULL
);

CREATE TABLE CC_BRANCH(
    CC_BR_ID VARCHAR(100) PRIMARY KEY
    ,CC_BR_CENTER_ID VARCHAR(100) references MSTR_COACH_CENTER(MC_CENTER_ID)
    ,CC_BR_NM VARCHAR(100) NOT NULL,
    ,CC_BR_ADDRESS VARCHAR(300)
    ,CC_BR_CITY VARCHAR(300) NOT NULL
    ,CC_BR_STATE VARCHAR(100) NOT NULL
    ,CC_BR_PIN INT NOT NULL
    ,CC_BR_COUNTRY VARCHAR(100) NOT NULL
    ,CC_BR_EMAILID VARCHAR(200) NOT NULL
    ,CC_BR_CONTACTNO VARCHAR(100) NOT NULL
);

CREATE TABLE MSTR_TEACHER(
    TCHR_ID VARCHAR(100) PRIMARY KEY
    ,TCHR_NM VARCHAR(100) NOT NULL
    ,TCHR_AADHAR VARCHAR(12) NOT NULL
    ,TCHR_PANCARD VARCHAR(10) NOT NULL
    ,TCHR_EMAILID VARCHAR(100) NOT NULL
    ,TCHR_CONTACTNO VARCHAR(100) NOT NULL
    ,TCHR_ADDRESS VARCHAR(300) NOT NULL
    ,TCHR_CITY VARCHAR(300) NOT NULL
    ,TCHR_STATE VARCHAR(100) NOT NULL
    ,TCHR_PIN INT NOT NULL
    ,TCHR_COUNTRY VARCHAR(100) NOT NULL
);

CREATE TABLE MSTR_PRNT(
    PRNT_ID VARCHAR(100) PRIMARY KEY
    ,PRNT_NM VARCHAR(100) NOT NULL
    ,PRNT_AADHAR VARCHAR(12) NOT NULL
    ,PRNT_EMAILID VARCHAR(100) NOT NULL
    ,PRNT_CONTACTNO VARCHAR(100) NOT NULL
    ,PRNT_ADDRESS VARCHAR(300) NOT NULL
    ,PRNT_CITY VARCHAR(300) NOT NULL
    ,PRNT_STATE VARCHAR(100) NOT NULL
    ,PRNT_PIN INT NOT NULL
    ,PRNT_COUNTRY VARCHAR(100) NOT NULL
);

CREATE TABLE MSTR_STU(
    STU_ID VARCHAR(100) PRIMARY KEY
    ,STU_NM VARCHAR(100) NOT NULL
    ,STU_AADHAR VARCHAR(12) NOT NULL
    ,STU_EMAILID VARCHAR(100) NOT NULL
    ,STU_CONTACTNO VARCHAR(100) NOT NULL
    ,STU_ADDRESS VARCHAR(300) NOT NULL
    ,STU_CITY VARCHAR(300) NOT NULL
    ,STU_STATE VARCHAR(100) NOT NULL
    ,STU_PIN INT NOT NULL
    ,STU_COUNTRY VARCHAR(100) NOT NULL
    ,STU_DOB VARCHAR(20) NOT NULL
    ,STU_PRNT_ID VARCHAR(100) references MSTR_PRNT(PRNT_ID)
);

CREATE TABLE MSRT_SUB(
    SUB_ID VARCHAR(100) PRIMARY KEY
    ,SUB_NAME VARCHAR(100) NOT NULL
    ,SUB_BOARD VARCHAR(10) NOT NULL
    ,SUB_CLASS VARCHAR(10) NOT NULL
    ,SUB_LANG VARCHAR(10) NOT NULL
);

CREATE TABLE MAP_TCHR_SUB(
    MTS_ID VARCHAR(100) PRIMARY KEY
    ,MTS_TCHR_ID VARCHAR(100) NOT NULL references MSTR_TEACHER(TCHR_ID)
    ,MTS_SUB VARCHAR(100) NOT NULL references MSRT_SUB(SUB_ID)
    ,MTS_BR_ID VARCHAR(100) NOT NULL references CC_BRANCH(CC_BR_ID)
)

CREATE TABLE MAP_STU_SUB(
    MSS_ID VARCHAR(100) PRIMARY KEY
    ,MSS_STU_ID VARCHAR(100) references MSTR_STU(STU_ID)
    ,MSS_STU_TCHR VARCHAR(100) references MAP_TCHR_SUB(MTS_ID)
    ,MSS_STU_DOW VARCHAR(10) 
    ,MSS_STU_TIME VARCHAR(20)
)
